services:
  - type: web
    name: nfl-picks
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: nfl-picks-db
          property: connectionString

databases:
  - name: nfl-picks-db
    plan: starter